#! /usr/bin/python3
# -*- coding: utf-8 -*-

PRIOR_LETV  = 1
PRIOR_SOHU  = 2
PRIOR_CNTV  = 3
PRIOR_QQ    = 4
PRIOR_WASU  = 4
PRIOR_PPTV  = 4
PRIOR_TVIE  = 4
PRIOR_CUTV  = 5
PRIOR_UCTV  = 6
PRIOR_DEFTV = 4
PRIOR_COMMON = 100
